library(ggplot2)
library(dplyr)
library(patchwork)

# Load the track and the benchmark output
track_data <- readRDS("scratch/simulated_seal_light_scenarios.rds")

# We will load the dataframes generated by the benchmark script
# Actually, since I didn't save the dataframes, I'll load the rds if it exists.
# Wait, I didn't save the rds of the results in the benchmark script! 
