#' Simulated 14-day GLS track
#'
#' A synthetic geolocator dataset for package testing and benchmarking.
#' Generated by \code{data-raw/simulate_tracks.R} with \code{set.seed(42)}.
#'
#' @format A data frame with one row per 10-minute observation:
#'   \describe{
#'     \item{time}{POSIXct timestamp (UTC)}
#'     \item{true_lat}{Ground-truth latitude (decimal degrees)}
#'     \item{true_lon}{Ground-truth longitude (decimal degrees)}
#'     \item{light}{Simulated observed light value (arbitrary units, 0--64)}
#'   }
#' @seealso \link{TwilightFreeSMC}, \link{TwilightFreeGrid}
"sim_short"

#' Simulated 28-day polar GLS track
#'
#' A synthetic geolocator dataset covering a high-latitude summer foray
#' (Alaska, ~55--70 N). Generated by \code{data-raw/simulate_tracks.R}.
#'
#' @format A data frame with one row per 10-minute observation:
#'   \describe{
#'     \item{time}{POSIXct timestamp (UTC)}
#'     \item{true_lat}{Ground-truth latitude (decimal degrees)}
#'     \item{true_lon}{Ground-truth longitude (decimal degrees)}
#'     \item{light}{Simulated observed light value (arbitrary units, 0--64)}
#'   }
#' @seealso \link{TwilightFreeSMC}, \link{TwilightFreeGrid}
"sim_polar"

#' Simulated 30-day equinox-crossing GLS track
#'
#' A synthetic geolocator dataset crossing the equator near the September
#' equinox, where geolocation latitude accuracy is lowest.
#' Generated by \code{data-raw/simulate_tracks.R}.
#'
#' @format A data frame with one row per 10-minute observation:
#'   \describe{
#'     \item{time}{POSIXct timestamp (UTC)}
#'     \item{true_lat}{Ground-truth latitude (decimal degrees)}
#'     \item{true_lon}{Ground-truth longitude (decimal degrees)}
#'     \item{light}{Simulated observed light value (arbitrary units, 0--64)}
#'   }
#' @seealso \link{TwilightFreeSMC}, \link{TwilightFreeGrid}
"sim_equinox"

#' Simulated 365-day long GLS track
#'
#' A synthetic full-year geolocator dataset spanning a Southern Ocean circuit.
#' Generated by \code{data-raw/simulate_tracks.R}.
#'
#' @format A data frame with one row per 10-minute observation:
#'   \describe{
#'     \item{time}{POSIXct timestamp (UTC)}
#'     \item{true_lat}{Ground-truth latitude (decimal degrees)}
#'     \item{true_lon}{Ground-truth longitude (decimal degrees)}
#'     \item{light}{Simulated observed light value (arbitrary units, 0--64)}
#'   }
#' @seealso \link{TwilightFreeSMC}, \link{TwilightFreeGrid}
"sim_long"
