# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib invTwilightFree, .registration = TRUE
NULL

#' Calculate the solar zenith angle (in degrees)
#'
#' @param unix_time Numeric vector of Unix timestamps (seconds since 1970-01-01 UTC)
#' @param lon Numeric vector of longitudes (decimal degrees)
#' @param lat Numeric vector of latitudes (decimal degrees)
#' @return Numeric vector of solar zenith angles (degrees; 0 = overhead, 90 = horizon)
#' @export
solar_zenith <- function(unix_time, lon, lat) .Call(wrap__solar_zenith, unix_time, lon, lat)

#' Calculate the log-likelihood of observed light given proposed tracks.
#' uses a spike-and-slab model for false light events.
#'
#' @param obs_light Observed light values
#' @param expected_light Expected maximum light values (from solar zenith)
#' @param lambda Decay rate for the shading exponential distribution
#' @param max_light Maximum possible light value for the tag
#' @param prob_slab Probability of a false light event (the slab)
#' @export
light_log_likelihood <- function(obs_light, expected_light, lambda, max_light, prob_slab) .Call(wrap__light_log_likelihood, obs_light, expected_light, lambda, max_light, prob_slab)

#' Run the Particle Filter Engine
#' 
#' Core SMC engine for TwilightFree track reconstruction.
#' 
#' @param unix_times Timestamps of observations
#' @param obs_light Observed light values
#' @param n_particles Number of particles to use
#' @param start_lat Starting Latitude
#' @param start_lon Starting Longitude
#' @param end_lat Ending Latitude (use NA if unknown)
#' @param end_lon Ending Longitude (use NA if unknown)
#' @param method Method to use: "guided", "ffbs", or "forward"
#' @param step_hours Hours between particle movement steps
#' @param diffusion Diffusion coefficient (kilometers per sqrt(day))
#' @param trans_prob Flattened row-major transition probability matrix for behavioral states
#' @param calibration c(intercept, slope)
#' @param likelihood_params c(lambda, max_light, prob_slab)
#' @param mask_matrix Flattened spatial mask matrix (0 = impassable); empty for no mask
#' @param mask_extent c(xmin, xmax, ymin, ymax) extent of the mask raster
#' @param mask_nrow Number of rows in the mask raster
#' @param mask_ncol Number of columns in the mask raster
#' @param seed Integer seed for reproducibility; 0 means non-deterministic (uses entropy)
#' @param aux_logl_flat Flattened aux log-likelihood raster (k_steps * nrow * ncol, row-major); empty for no aux
#' @param aux_extent c(xmin, xmax, ymin, ymax) extent of the aux raster
#' @param aux_nrow Number of rows in the aux raster
#' @param aux_ncol Number of columns in the aux raster
#' @param flat_light_threshold Light-range threshold (max_obs - min_obs) below which a knot is
#'   classified as informationally flat (no visible twilight). Diffusion is scaled by
#'   `flat_light_scale` on such knots to prevent unconstrained wandering when the light
#'   carries no positional signal. Default 10.0 (raw light units).
#' @param flat_light_scale Multiplicative scale applied to the diffusion coefficient on flat-light
#'   knots (see `flat_light_threshold`). Values in (0, 1) constrain movement; 1.0 disables the
#'   heuristic. Default 0.1 (10x tighter).
#' @name run_particle_filter
#' @export
run_particle_filter <- function(unix_times, obs_light, n_particles, start_lat, start_lon, end_lat, end_lon, method, step_hours, diffusion, trans_prob, calibration, likelihood_params, mask_matrix, mask_extent, mask_nrow, mask_ncol, seed, aux_logl_flat, aux_extent, aux_nrow, aux_ncol, flat_light_threshold, flat_light_scale) .Call(wrap__run_particle_filter, unix_times, obs_light, n_particles, start_lat, start_lon, end_lat, end_lon, method, step_hours, diffusion, trans_prob, calibration, likelihood_params, mask_matrix, mask_extent, mask_nrow, mask_ncol, seed, aux_logl_flat, aux_extent, aux_nrow, aux_ncol, flat_light_threshold, flat_light_scale)

#' Evaluate the spike-and-slab log-likelihood over a grid of locations
#'
#' For each candidate location, returns the summed log-likelihood of the
#' observed light series under the continuous spike-and-slab model. Useful for
#' visualising the likelihood surface independently of the HMM smoother.
#'
#' @param lon Longitudes of grid cells (degrees)
#' @param lat Latitudes of grid cells (degrees)
#' @param unix_times Observation timestamps (seconds since 1970-01-01)
#' @param obs_light Observed light values
#' @param calibration c(intercept, slope)
#' @param likelihood_params c(lambda, max_light, prob_slab) or c(lambda, max_light, alpha, beta)
#' @return Numeric vector of log-likelihoods, one per grid cell
#' @name eval_logpk_grid
#' @export
eval_logpk_grid <- function(lon, lat, unix_times, obs_light, calibration, likelihood_params) .Call(wrap__eval_logpk_grid, lon, lat, unix_times, obs_light, calibration, likelihood_params)

run_grid_hmm <- function(lon, lat, knot_times, obs_times, obs_light, fixed_idx, fixed_lon, fixed_lat, diffusion, trans_prob, calibration, likelihood_params, aux_logl) .Call(wrap__run_grid_hmm, lon, lat, knot_times, obs_times, obs_light, fixed_idx, fixed_lon, fixed_lat, diffusion, trans_prob, calibration, likelihood_params, aux_logl)

# nolint end
