# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib invTwilightFree, .registration = TRUE
NULL

#' Calculate the solar zenith angle (in degrees)
#'
#' @param unix_time Numeric vector of Unix timestamps (seconds since 1970-01-01 UTC)
#' @param lon Numeric vector of longitudes (decimal degrees)
#' @param lat Numeric vector of latitudes (decimal degrees)
#' @return Numeric vector of solar zenith angles (degrees; 0 = overhead, 90 = horizon)
#' @export
solar_zenith <- function(unix_time, lon, lat) .Call(wrap__solar_zenith, unix_time, lon, lat)

#' Calculate the log-likelihood of observed light given proposed tracks.
#' uses a spike-and-slab model for false light events.
#'
#' @param obs_light Observed light values
#' @param expected_light Expected maximum light values (from solar zenith)
#' @param lambda Decay rate for the shading exponential distribution
#' @param max_light Maximum possible light value for the tag
#' @param prob_slab Probability of a false light event (the slab)
#' @param shade_ratio Ratio of the upper-arm decay rate to the shading rate
#'   (2 is the historical fixed value)
#' @export
light_log_likelihood <- function(obs_light, expected_light, lambda, max_light, prob_slab, shade_ratio) .Call(wrap__light_log_likelihood, obs_light, expected_light, lambda, max_light, prob_slab, shade_ratio)

#' Run the Particle Filter Engine
#' 
#' Core SMC engine for TwilightFree track reconstruction.
#' 
#' @param unix_times Timestamps of observations
#' @param obs_light Observed light values
#' @param n_particles Number of particles to use
#' @param start_lat Starting Latitude
#' @param start_lon Starting Longitude
#' @param end_lat Ending Latitude (use NA if unknown)
#' @param end_lon Ending Longitude (use NA if unknown)
#' @param method Method to use: "guided", "ffbs", or "forward"
#' @param step_hours Hours between particle movement steps
#' @param diffusion Diffusion coefficient (kilometers per sqrt(day))
#' @param trans_prob Flattened row-major transition probability matrix for behavioral states
#' @param calibration Response parameters: `c(intercept, slope)` for the clamped-linear
#'   model, or `c(floor, amp, z50, scale)` for the logistic model (see details in
#'   `fit_light_response`). Length selects the model.
#' @param likelihood_params c(lambda, max_light, prob_slab)
#' @param shade_ratio Ratio of the upper-arm decay rate to the shading rate,
#'   i.e. lam_hi / lam_lo. 2 reproduces the previous fixed behaviour. Values
#'   below 1 make the shading tail heavier, which is what a continuously
#'   diving animal needs: most of its record is far below the clear-sky
#'   expectation and should be cheap to explain.
#' @param mask_matrix Flattened spatial mask matrix (0 = impassable); empty for no mask
#' @param mask_extent c(xmin, xmax, ymin, ymax) extent of the mask raster
#' @param mask_nrow Number of rows in the mask raster
#' @param mask_ncol Number of columns in the mask raster
#' @param seed Integer seed for reproducibility; 0 means non-deterministic (uses entropy)
#' @param aux_logl_flat Flattened aux log-likelihood raster (k_steps * nrow * ncol, row-major); empty for no aux
#' @param aux_extent c(xmin, xmax, ymin, ymax) extent of the aux raster
#' @param aux_nrow Number of rows in the aux raster
#' @param aux_ncol Number of columns in the aux raster
#' @param flat_light_threshold Light-range threshold (max_obs - min_obs) below which a knot is
#'   classified as informationally flat (no visible twilight). Diffusion is scaled by
#'   `flat_light_scale` on such knots to prevent unconstrained wandering when the light
#'   carries no positional signal. Default 10.0 (raw light units).
#' @param flat_light_scale Multiplicative scale applied to the diffusion coefficient on flat-light
#'   knots (see `flat_light_threshold`). Values in (0, 1) constrain movement; 1.0 disables the
#'   heuristic. Default 0.1 (10x tighter).
#' @name run_particle_filter
#' @export
run_particle_filter <- function(unix_times, obs_light, n_particles, start_lat, start_lon, end_lat, end_lon, method, step_hours, diffusion, trans_prob, calibration, likelihood_params, shade_ratio, mask_matrix, mask_extent, mask_nrow, mask_ncol, seed, aux_logl_flat, aux_extent, aux_nrow, aux_ncol, flat_light_threshold, flat_light_scale) .Call(wrap__run_particle_filter, unix_times, obs_light, n_particles, start_lat, start_lon, end_lat, end_lon, method, step_hours, diffusion, trans_prob, calibration, likelihood_params, shade_ratio, mask_matrix, mask_extent, mask_nrow, mask_ncol, seed, aux_logl_flat, aux_extent, aux_nrow, aux_ncol, flat_light_threshold, flat_light_scale)

#' Evaluate the spike-and-slab log-likelihood over a grid of locations
#'
#' For each candidate location, returns the summed log-likelihood of the
#' observed light series under the continuous spike-and-slab model. Useful for
#' visualising the likelihood surface independently of the HMM smoother.
#'
#' @param lon Longitudes of grid cells (degrees)
#' @param lat Latitudes of grid cells (degrees)
#' @param unix_times Observation timestamps (seconds since 1970-01-01)
#' @param obs_light Observed light values
#' @param calibration Response parameters: `c(intercept, slope)` for the clamped-linear
#'   model, or `c(floor, amp, z50, scale)` for the logistic model (see details in
#'   `fit_light_response`). Length selects the model.
#' @param likelihood_params c(lambda, max_light, prob_slab) or c(lambda, max_light, alpha, beta)
#' @param shade_ratio Ratio of the spike's upper-arm decay rate to its shading
#'   (lower-arm) rate. Pass **2** to match `TwilightFreeGrid()`'s default; the
#'   engines' own value if you are reproducing a specific fit. There is no
#'   cell-count argument -- the number of cells is `length(lon)` -- so a value
#'   intended as `n_cells` silently lands here instead, and a large `shade_ratio`
#'   makes observations above the expected curve enormously expensive, which
#'   biases the profile toward positions that over-predict light (poleward in
#'   summer). Always profile a matched-response control: it peaks off the truth
#'   when this is wrong.
#' @return Numeric vector of log-likelihoods, one per grid cell
#' @name eval_logpk_grid
#' @export
eval_logpk_grid <- function(lon, lat, unix_times, obs_light, calibration, likelihood_params, shade_ratio) .Call(wrap__eval_logpk_grid, lon, lat, unix_times, obs_light, calibration, likelihood_params, shade_ratio)

run_grid_hmm <- function(lon, lat, knot_times, obs_times, obs_light, fixed_idx, fixed_lon, fixed_lat, diffusion, diffusion_lon, trans_prob, calibration, likelihood_params, shade_ratio, aux_logl, area_correction, lambda_scale) .Call(wrap__run_grid_hmm, lon, lat, knot_times, obs_times, obs_light, fixed_idx, fixed_lon, fixed_lat, diffusion, diffusion_lon, trans_prob, calibration, likelihood_params, shade_ratio, aux_logl, area_correction, lambda_scale)

#' Run the native single-track block + polish sampler.
#'
#' @param knot_obs_start 0-based start index of each knot's contiguous obs block
#' @param knot_obs_len number of observations in each knot
#' @param obs_times observation timestamps (seconds since 1970)
#' @param obs_light observed light values (processed as by the R fit)
#' @param calibration Response parameters: `c(intercept, slope)` for the clamped-linear
#'   model, or `c(floor, amp, z50, scale)` for the logistic model (see details in
#'   `fit_light_response`). Length selects the model.
#' @param likelihood_params c(lambda, max_light, prob_slab)
#' @param surr_mu per-knot surrogate mean, length 2K (lon, lat interleaved)
#' @param surr_p per-knot surrogate 2x2 precision, length 4K (row-major)
#' @param p_move movement precision (2x2, row-major)
#' @param start_lon Fixed first-knot longitude
#' @param start_lat Fixed first-knot latitude
#' @param block_len Maximum block length (knots)
#' @param sweeps Total sweeps
#' @param burn Burn-in sweeps
#' @param thin Thinning interval
#' @param polish Whether to run the red-black single-site polish each sweep
#' @param seed RNG seed; 0 means entropy
#' @return List of per-knot posterior mean_lon, sd_lon, mean_lat, sd_lat, plus accept and n_kept
#' @name run_block_track
run_block_track <- function(knot_obs_start, knot_obs_len, obs_times, obs_light, calibration, likelihood_params, surr_mu, surr_p, p_move, start_lon, start_lat, block_len, sweeps, burn, thin, polish, seed) .Call(wrap__run_block_track, knot_obs_start, knot_obs_len, obs_times, obs_light, calibration, likelihood_params, surr_mu, surr_p, p_move, start_lon, start_lat, block_len, sweeps, burn, thin, polish, seed)

#' Native hierarchical partial-pooling sampler over a panel of tracks.
#'
#' Runs the whole Gibbs sweep natively: each individual's track is updated with
#' the block+polish kernel conditional on its movement variance sig2_i, then
#' sig2_i and the population scale beta are drawn from their conjugate
#' full-conditionals. All arrays concatenate the individuals; knots_per_ind gives
#' each individual's knot count, and knot_obs_start indexes the GLOBAL obs arrays.
#'
#' @param n_ind Number of individuals
#' @param knots_per_ind Knot count per individual (length n_ind)
#' @param knot_obs_start Per-knot global obs start index (length sum knots_per_ind)
#' @param knot_obs_len Per-knot obs count
#' @param obs_times Global concatenated observation timestamps
#' @param obs_light Global concatenated observed light
#' @param cal Per-individual response parameters, packed contiguously: length
#'   2*n_ind for the clamped-linear model or 4*n_ind for the logistic one.
#' @param lp Per-individual c(lambda, max_light, prob_slab), length 3*n_ind
#' @param surr_mu Per-knot surrogate mean (2 per knot)
#' @param surr_p Per-knot surrogate 2x2 precision (4 per knot)
#' @param cinv Per-individual movement shape precision Cinv (2x2), length 4*n_ind
#' @param start_lon Per-individual fixed first-knot (deploy) longitude
#' @param start_lat Per-individual fixed first-knot (deploy) latitude
#' @param end_lon Per-individual fixed last-knot (retrieval) longitude; NaN = free
#' @param end_lat Per-individual fixed last-knot (retrieval) latitude; NaN = free
#' @param aux_flat Concatenated per-tag additive location log-likelihood (sensor
#'   terms), each tag a K*ncell block on its own regular lon/lat grid; empty for none
#' @param aux_ncol,aux_nrow Per-tag aux grid dimensions (0 columns/rows = no terms)
#' @param aux_lon0,aux_dlon,aux_lat0,aux_dlat Per-tag aux grid origin and spacing
#' @param a_pop InvGamma shape for sig2_i
#' @param g0 Gamma shape hyperprior for beta
#' @param h0 Gamma rate hyperprior for beta
#' @param block_len Maximum block length
#' @param sweeps Total sweeps
#' @param burn Burn-in sweeps
#' @param thin Thinning interval
#' @param polish Whether to run the red-black polish each sweep
#' @param spherical Great-circle movement metric (exp(-gcdist^2/2 sig2)) if TRUE,
#'   else the flat tangent-plane metric at each tag's reference latitude
#' @param crw Correlated random walk: model the increments as an AR(1),
#'   delta_t = rho*delta_{t-1} + eps, with a per-tag persistence rho sampled
#'   alongside the movement variance. FALSE gives the memoryless Brownian walk
#'   and is bit-identical to the previous behaviour.
#' @param rho_prior_sd Standard deviation of the mean-zero normal prior on each
#'   tag's persistence
#' @param rho_max Persistence is confined to (-rho_max, rho_max). Values near 1
#'   are near-non-stationary: displacement then grows like n^1.5 rather than
#'   sqrt(n), so a track can leave the surrogate mesh entirely.
#' @param seed RNG seed; 0 means entropy
#' @return List with beta and sig2 (kept draws), plus per-knot track posterior
#'   mean_lon/sd_lon/mean_lat/sd_lat (concatenated across individuals, same order
#'   as knots_per_ind), and rho (per-tag persistence draws, zero when crw is FALSE)
#' @name run_block_hier
run_block_hier <- function(n_ind, knots_per_ind, knot_obs_start, knot_obs_len, obs_times, obs_light, cal, lp, surr_mu, surr_p, cinv, start_lon, start_lat, end_lon, end_lat, aux_flat, aux_ncol, aux_nrow, aux_lon0, aux_dlon, aux_lat0, aux_dlat, a_pop, g0, h0, block_len, sweeps, burn, thin, polish, spherical, crw, rho_prior_sd, rho_max, shade_ratio, seed) .Call(wrap__run_block_hier, n_ind, knots_per_ind, knot_obs_start, knot_obs_len, obs_times, obs_light, cal, lp, surr_mu, surr_p, cinv, start_lon, start_lat, end_lon, end_lat, aux_flat, aux_ncol, aux_nrow, aux_lon0, aux_dlon, aux_lat0, aux_dlat, a_pop, g0, h0, block_len, sweeps, burn, thin, polish, spherical, crw, rho_prior_sd, rho_max, shade_ratio, seed)

# nolint end
